
package ua.artcode.testio.soap.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentEndpoint", targetNamespace = "http://endpoint.soap.testio.artcode.ua/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentEndpoint {


    /**
     * 
     * @param arg0
     * @return
     *     returns ua.artcode.testio.soap.endpoint.StudentDTO
     * @throws NoStudentFoundException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://endpoint.soap.testio.artcode.ua/StudentEndpoint/getStudentInfoRequest", output = "http://endpoint.soap.testio.artcode.ua/StudentEndpoint/getStudentInfoResponse", fault = {
        @FaultAction(className = NoStudentFoundException_Exception.class, value = "http://endpoint.soap.testio.artcode.ua/StudentEndpoint/getStudentInfo/Fault/NoStudentFoundException")
    })
    public StudentDTO getStudentInfo(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0)
        throws NoStudentFoundException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns ua.artcode.testio.soap.endpoint.StudentDTO
     * @throws NoStudentFoundException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://endpoint.soap.testio.artcode.ua/StudentEndpoint/loginRequest", output = "http://endpoint.soap.testio.artcode.ua/StudentEndpoint/loginResponse", fault = {
        @FaultAction(className = NoStudentFoundException_Exception.class, value = "http://endpoint.soap.testio.artcode.ua/StudentEndpoint/login/Fault/NoStudentFoundException")
    })
    public StudentDTO login(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws NoStudentFoundException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns ua.artcode.testio.soap.endpoint.StudentList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://endpoint.soap.testio.artcode.ua/StudentEndpoint/getAllRequest", output = "http://endpoint.soap.testio.artcode.ua/StudentEndpoint/getAllResponse")
    public StudentList getAll(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns ua.artcode.testio.soap.endpoint.StudentDTO
     * @throws RegisterException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://endpoint.soap.testio.artcode.ua/StudentEndpoint/registerRequest", output = "http://endpoint.soap.testio.artcode.ua/StudentEndpoint/registerResponse", fault = {
        @FaultAction(className = RegisterException_Exception.class, value = "http://endpoint.soap.testio.artcode.ua/StudentEndpoint/register/Fault/RegisterException")
    })
    public StudentDTO register(
        @WebParam(name = "arg0", partName = "arg0")
        StudentDTO arg0)
        throws RegisterException_Exception
    ;

}
